document.write("A idade do Flávio é ");
document.write(20 + 24);
document.write("<br> Flávio nasceu em " + (2021 - 44));
document.write("<br>");
document.write("Joaquim nasceu em " + (2021 - 25) + "<br>");
document.write("Barney nasceu em " + (2021 - 45) + "<br>");
document.write("Flávio tem " + (2021 - 1977) + " anos <br>");
document.write("Joaquim tem " + (2021 - 1996) + " anos <br>");
document.write("Barney tem " + (2021 - 1976) + " anos <br>");
document.write("<br> A média das idades é ");
document.write((44 + 25 + 45)/3);
document.write("<br> A soma das idades é " + (44 + 25 + 45) + "<br>");